{{- if .Values.configmap.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "se-deployment.name" . }}
  labels:
    {{- include "se-deployment.labels" . | nindent 4 }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
immutable: {{ .Values.configmap.immutable }}
{{- end }}
