{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "se-deployment.name" . }}
  labels:
    {{- include "se-deployment.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "se-deployment.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  jobLabel: {{ include "se-deployment.name" . }}
  endpoints:
    - port: http
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      targetPort: http
    {{- if .Values.service.metricsPort.enabled }}
    - port: metrics
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      targetPort: metrics
    {{- end }}
{{- end }}
