{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "se-deployment.name" . }}
  labels:
    {{- include "se-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.metricsPort.enabled }}
    - port: {{ .Values.service.metricsPort.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{ end }}
  selector:
    {{- include "se-deployment.selectorLabels" . | nindent 4 }}
{{- end }}
