{{- if and .Values.keda.enabled .Values.keda.authentication.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "se-deployment.name" $ }}
  labels:
    {{- include "se-deployment.labels" $ | nindent 4 }}
spec:
  {{- with .Values.keda.authentication.secretTargetRef }}
  secretTargetRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
